settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 8080
  host: localhost
schema:
  - name: app
    path: .
    commands:
      install:
        status: true
        method: go build -o attendance-management
      run:
        status: true
        method: /go/bin/dlv
    args:
      - --headless=true
      - --listen=:2345
      - --api-version=2
      - exec
      - ./attendance-management
    watcher:
      extensions:
        - go
      paths:
        - /
      ignore:
        paths:
          - ./frontend
          - .git
          - .realize
          - vendor
