settings:
  legacy:
    force: false
    interval: 0ms
schema:
  - name: app
    path: .
    commands:
      install:
        status: true
        method: go build -o attendance-management
      run:
        status: true
        method: /go/bin/dlv
    args:
      - exec
      - ./attendance-management
      - --headless=true
      - --listen=:2345
      - --api-version=2
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - ./frontend
        - .git
        - .realize
        - vendor
        - .idea
        - ./docker
