version: '3.7'

services:
  app:
    build:
      context: ./
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DB_CONNECTION_NAME=tcp(mysql-container:3306)
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_TABLE=attendance_management
      - FIREBASE_SERVICE_JSON=${FIREBASE_SERVICE}
      #- GIN_MODE=release

  mysql:
    container_name: mysql-container
    image: mysql
    volumes:
      - "./docker/mysql/db:/var/lib/mysql"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: attendance_management
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  mysql:

