version: '3'

services:
  db:
    image: mysql
    volumes:
      - "./docker/mysql/db:/var/lib/mysql"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: attendance_management
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  db:

