version: '3.7'

services:
  app:
    container_name: go-app
    build:
      context: ./
    volumes:
      - ./:/go/app
    command: realize start --run
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:2345:2345"
    env_file:
      - .env
    environment:
      - DB_CONNECTION_NAME=${DB_CONNECTION_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TABLE=${DB_TABLE}
      - FIREBASE_SERVICE_JSON=${FIREBASE_SERVICE}

  mysql:
    container_name: mysql-db
    image: mysql
    volumes:
      - "./docker/mysql/db:/var/lib/mysql"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: attendance_management
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  mysql:
  app:

