version: '3.7'

services:
  app:
    container_name: go-app
    build:
      context: .
      dockerfile: docker/go/${DIR_ENV}/Dockerfile
    volumes:
      - ./:/go/src
    command: ${DOCKER_RUN_COMMAND}
    depends_on:
      - mysql
    ports:
      - 8080:8080
      - 2345:2345
    env_file:
      - .env
    environment:
      - DB_TCP_HOST=${DB_TCP_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - FIREBASE_SERVICE_JSON=${FIREBASE_SERVICE}

  mysql:
    container_name: mysql-db
    image: mysql
    volumes:
      - "./docker/mysql/db:/var/lib/mysql"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: attendance_management
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

volumes:
  mysql:
  app:

