pkgname="database"
output="database/gen"
add-global-variants=true
add-panic-variants=true
[mysql]
  dbname  = "attendance_management"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = "root"
  sslmode = "false"
  black_list=["schema_migrations"]
