# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

commands:
  go_mod_download:
    steps:
      - restore_cache:
          name: Restore go modules cache
          keys:
            - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      - save_cache:
          name: Save go modules cache
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  migrate_db:
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m -wait-retry-interval 5s

      - run:
          command: /go/migrate -source file://infrastructure/sqlstore/migrations/  -database 'mysql://root:root@tcp(localhost:3306)/test_attendance_management' up

      - run:
          name: Run go test
          command: go test -v ./...

jobs:
  build:
    parallelism: 1
    docker:
      - image: kout127/golang-with-migrate:0.0.5
        environment:
          DB_TCP_HOST: localhost:3306
          DB_USER: root
          DB_PASS: root
          DB_NAME: test_attendance_management
          TEST_DB_NAME: test_attendance_management
      - image: tkuchiki/delayed-mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATABASE: test_attendance_management



    working_directory: /go/src/github.com/KouT127/attendance-management
    steps:
      - checkout
      - go_mod_download
      - migrate_db

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop