database:
  dbms:   "mysql"
  user:   "root"
  pass:   ""
  host:   "localhost"
  port:   "3306"
  dbName: "attendance_management"
  option: "charset=utf8&parseTime=true"

application:
  isDebug: True